from database import SessionLocal
from models import Detection


# Reference location from Google Maps
BASE_LAT = 19.0251000
BASE_LON = 73.0896393


test_detections = [
    {
        "class_name": "Ghost Net",
        "confidence": 0.91,
        "latitude": 19.0251449661,
        "longitude": 73.0896393000,
        "dimensions": "2.4m x 1.1m",
        "survey_id": "AR-TEST-01",
        "status": "DRIFTING",
        "missed_cycles": 0,
    },
    {
        "class_name": "Bottle",
        "confidence": 0.78,
        "latitude": 19.0251000000,
        "longitude": 73.0897344285,
        "dimensions": "0.3m x 0.1m",
        "survey_id": "AR-TEST-01",
        "status": "CONFIRMED",
        "missed_cycles": 0,
    },
    {
        "class_name": "Tire",
        "confidence": 0.83,
        "latitude": 19.0249651018,
        "longitude": 73.0896393000,
        "dimensions": "0.7m x 0.7m",
        "survey_id": "AR-TEST-01",
        "status": "STATIONARY",
        "missed_cycles": 0,
    },
]


def insert_test_detections():
    db = SessionLocal()

    try:
        for data in test_detections:
            detection = Detection(**data)
            db.add(detection)

        db.commit()

        print("Test detections inserted successfully!")

        # Show the IDs generated by the database
        for detection in db.query(Detection).filter(
            Detection.survey_id == "AR-TEST-01"
        ).all():
            print(
                f"ID: {detection.id} | "
                f"{detection.class_name} | "
                f"Status: {detection.status} | "
                f"Lat: {detection.latitude} | "
                f"Lon: {detection.longitude}"
            )

    except Exception as e:
        db.rollback()
        print("Error inserting test detections:")
        print(e)

    finally:
        db.close()


if __name__ == "__main__":
    insert_test_detections()